apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.db.rootPassword | b64enc }}
  MYSQL_DATABASE: {{ .Values.secret.db.database | b64enc}}
kind: Secret
metadata:
  name: {{ .Values.secret.db.name }}
type: Opaque
---
apiVersion: v1
data:
  SPRING_DATASOURCE_URL: {{ .Values.secret.app.url | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.app.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.app.password | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.secret.app.name }}
type: Opaque

